apiVersion: v1
kind: Service
metadata:
  name: hms-frontend
  labels:
    app: hms-frontend
spec:
  # Change type to ClusterIP or NodePort if your environment needs that instead of LoadBalancer
  type: LoadBalancer
  selector:
    app: hms-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
